### ISSUE TITLE
toJSON is Slow

### ISSUE THREAD

**Issue by danj1980** [tugrul/aspjson#2]
Firstly, thanks for creating this code.

Small issue though. I have an array containing two entries which are both jsObjects containing 5 entries each. When I pass the Results array to toJSON shown below, it adds 1000ms to the execution time.

If I create a jsObject and set **myJSObject("myresults") = Results**, and myJSObject.flush, the execution time is only 34ms in total, but then the format is not correct as it includes the 'myresults' field name in the output.

```
'tblResults is an ADODB RecordSet.

dim Results()
redim Results(-1)
dim Result

do until tblResults.eof
	set Result = jsObject()

	Result("tenancyid") = tblResults("tenancyid")	
	if tblResults("company") <> "" then
		Result("fullname") = tblResults("company")
	else
		Result("fullname") = tblResults("firstname") & " " & tblResults("surname")
	end if

	Result("apartmentnumber") = tblResults("namenumber")
	Result("blockname") = tblResults("blockname")
	Result("postcode") = tblResults("postcode")
	
	redim preserve Results(ubound(Results)+1)
	set Results(ubound(Results)) = Result
	
	tblResults.movenext
loop

ResultsJson = toJSON(Results)

response.write ResultsJson

```

**Comment by ronald-mz** [comment]
#7 Should improve toJSON times.

String concats are very slow for large strings in vbscript. With #7 merged, the library has moved from using string concats to a buffer to generate the stringified JSON.

**Comment by ronald-mz** [comment]
@tugrul You can likely close this issue.

**Comment by tugrul** [comment]
Thanks @RonaldZielaznicki
