### ISSUE TITLE
No leading zero before decimal point: Conformance issue with ECMA-404

### ISSUE THREAD

**Issue by genezx** [tugrul/aspjson#3]
set o = jsobject()
o("a")= 0.123
WScript.Echo toJSON(o)
' Output: {"a":.123} which is invalid because ECMA-404 does not allow numbers starting with decimal point.

**Comment by tugrul** [comment]
@RonaldZielaznicki do you wanna make this change? My VBScript skills have weakened over the years. I'm not motivated to make changes for this reason

**Comment by cuixiping** [comment]
The fix of @RonaldZielaznicki is not correct.

```vbs
Set o = jsArray()
o(Null) = 0.2
o(Null) = -0.3
Response.Write o.jsString
```

output `[00.2, -0-0.3]` on my testing.

This is my fix:

```vbs
	Case 4, 5 ' Single, Double
		dim s
		s = CStr(vPair)
		If Mid(s, 1, 1) = "." Then
			s = "0" & s
		ElseIf Mid(s, 1, 2) = "-." Then
			s = "-0" & Mid(s, 2)
		End If
		out.WriteText s
```
